name: Foundry CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  foundry:
    name: Run Foundry Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          ~/.foundry/bin/foundryup

      - name: Run forge build
        run: ~/.foundry/bin/forge build

      - name: Run forge tests
        run: ~/.foundry/bin/forge test
